//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCS.AdventureWorks.Services.Products.ProductsModel
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    // HACK Maually added.
    // Need the attributes because of https://github.com/npgsql/EntityFramework6.Npgsql/issues/88
    [Table("ProductProductPhoto", Schema = "Production")]
    public partial class ProductProductPhoto
    {
        [Key]
        [Column(Order = 0)]
        public int ProductID { get; set; }

        [Key]
        [Column(Order = 1)]
        public int ProductPhotoID { get; set; }

        [Column(Order = 2)]
        public bool Primary { get; set; }

        [Column(Order = 3)]
        public System.DateTime ModifiedDate { get; set; }

        [Column(Order = 4)]
        public virtual Product Product { get; set; }

        [Column(Order = 5)]
        public virtual ProductPhoto ProductPhoto { get; set; }
    }
}
